"""
Google Vertex AI Imagen을 활용한 실제 이미지 생성
minah 프로젝트의 Vertex AI 설정을 활용
"""

import os
import asyncio
from datetime import datetime
from typing import Dict, Any, Optional
import vertexai
from vertexai.preview.vision_models import ImageGenerationModel, Image
import base64
from io import BytesIO
from PIL import Image as PILImage


class VertexAIImageGenerator:
    """Google Vertex AI Imagen 이미지 생성기"""
    
    def __init__(self, project_id: str = "virtual-muse-466706-v2", location: str = "us-central1"):
        self.project_id = project_id
        self.location = location
        
        # Google Cloud 인증 설정
        key_path = os.path.join(os.path.dirname(__file__), "key.json")
        if os.path.exists(key_path):
            os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = key_path
            print(f"Google Cloud 키 파일 설정: {key_path}")
        else:
            print(f"key.json 파일을 찾을 수 없습니다: {key_path}")
        
        # Vertex AI 초기화
        vertexai.init(project=project_id, location=location)
        
        # 이미지 생성 모델 로드
        self.model = ImageGenerationModel.from_pretrained("imagegeneration@006")
        
        print(f"OK: Vertex AI 초기화 완료: {project_id} ({location})")
    
    async def generate_image(self, prompt: str, style: str = "modern", 
                           room_layout: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Vertex AI로 실제 이미지 생성"""
        
        try:
            print(f"CREATE: Vertex AI 이미지 생성 시작...")
            print(f"   - 스타일: {style}")
            print(f"   - 프롬프트 길이: {len(prompt)} 문자")
            
            # 비동기 처리를 위해 별도 스레드에서 실행
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, self._generate_sync, prompt, style, room_layout)
            
            return result
            
        except Exception as e:
            print(f"ERROR: Vertex AI 이미지 생성 실패: {e}")
            return {
                "success": False,
                "error": str(e),
                "service": "vertex_ai"
            }
    
    def _generate_sync(self, prompt: str, style: str, room_layout: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """동기 방식으로 이미지 생성 (스레드에서 실행)"""
        
        try:
            # Vertex AI 이미지 생성 파라미터
            generation_params = {
                "number_of_images": 1,
                "aspect_ratio": "1:1",  # 정사각형
                "safety_filter_level": "block_some",
                "person_generation": "dont_allow"  # 사람 생성 금지
            }
            
            # 스타일별 추가 파라미터
            if style == "modern":
                generation_params["guidance_scale"] = 15  # 높은 가이던스 (정확도 우선)
            elif style == "scandinavian":
                generation_params["guidance_scale"] = 12  # 중간 가이던스 (자연스러움)
            elif style == "industrial":
                generation_params["guidance_scale"] = 18  # 최고 가이던스 (강한 스타일)
            
            print(f"RUNNING: Vertex AI 호출 중... (guidance: {generation_params.get('guidance_scale', 10)})")
            
            # 실제 이미지 생성
            response = self.model.generate_images(
                prompt=prompt,
                **generation_params
            )
            
            if response.images:
                # 첫 번째 이미지 저장
                generated_image = response.images[0]
                
                # 파일명 생성
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"vertex_{style}_{timestamp}.png"
                
                # 저장 디렉토리 생성
                save_dir = "generated_images"
                os.makedirs(save_dir, exist_ok=True)
                
                # 이미지 저장
                filepath = os.path.join(save_dir, filename)
                generated_image.save(location=filepath, include_generation_parameters=False)
                
                print(f"OK: Vertex AI 이미지 생성 완료: {filepath}")
                
                return {
                    "success": True,
                    "image_path": filepath,
                    "filename": filename,
                    "service": "vertex_ai",
                    "parameters": generation_params,
                    "generation_time": "2-5초" # Vertex AI는 보통 빠름
                }
            else:
                return {
                    "success": False,
                    "error": "No images generated by Vertex AI",
                    "service": "vertex_ai"
                }
                
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "service": "vertex_ai"
            }
    
    async def generate_multiple_styles(self, base_prompt: str, 
                                     styles: list = ["modern", "scandinavian", "industrial"]) -> Dict[str, Any]:
        """여러 스타일로 동시 이미지 생성"""
        
        print(f"CREATE: {len(styles)}가지 스타일 동시 생성...")
        
        tasks = []
        for style in styles:
            # 스타일별 프롬프트 조정
            style_prompt = self._adjust_prompt_for_style(base_prompt, style)
            task = self.generate_image(style_prompt, style)
            tasks.append(task)
        
        # 모든 스타일 동시 생성
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # 결과 정리
        style_results = {}
        for i, style in enumerate(styles):
            if isinstance(results[i], Exception):
                style_results[style] = {
                    "success": False,
                    "error": str(results[i])
                }
            else:
                style_results[style] = results[i]
        
        return {
            "multi_style_generation": True,
            "total_styles": len(styles),
            "results": style_results,
            "successful_generations": sum(1 for r in style_results.values() if r.get("success", False))
        }
    
    def _adjust_prompt_for_style(self, base_prompt: str, style: str) -> str:
        """스타일에 맞게 프롬프트 조정"""
        
        style_adjustments = {
            "modern": ", sleek and minimalist design, clean lines, neutral colors, high-end finishes",
            "scandinavian": ", cozy hygge atmosphere, natural wood textures, soft pastels, warm lighting",
            "industrial": ", raw materials, exposed elements, dark tones, metal accents, urban loft style"
        }
        
        adjustment = style_adjustments.get(style, "")
        return base_prompt + adjustment


# 테스트 함수
async def test_vertex_ai_generation():
    """Vertex AI 이미지 생성 테스트"""
    
    generator = VertexAIImageGenerator()
    
    test_prompt = """
    Modern Korean interior room design:
    - Room dimensions: 4.0m × 5.0m × 2.8m
    - Sofa positioned in the center-left area of the room
    - Coffee table in the middle area of the room  
    - TV stand against the back wall
    - Clean white walls with light wood flooring
    - Bright natural lighting from large windows
    - Professional interior photography, 8K quality
    """
    
    print("TEST: Vertex AI 단일 이미지 생성 테스트...")
    result = await generator.generate_image(test_prompt, "modern")
    
    if result["success"]:
        print(f"OK: 성공: {result['image_path']}")
    else:
        print(f"ERROR: 실패: {result['error']}")
    
    print("\nTEST: 멀티 스타일 생성 테스트...")
    multi_result = await generator.generate_multiple_styles(test_prompt)
    
    print(f"총 {multi_result['successful_generations']}/{multi_result['total_styles']} 성공")
    for style, style_result in multi_result['results'].items():
        if style_result['success']:
            print(f"  OK: {style}: {style_result['image_path']}")
        else:
            print(f"  ERROR: {style}: {style_result['error']}")


if __name__ == "__main__":
    print("LAUNCH: Vertex AI 이미지 생성기 테스트 시작...")
    asyncio.run(test_vertex_ai_generation())