server {
    listen 80;
    server_name eunbie.site www.eunbie.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name eunbie.site www.eunbie.site;

    ssl_certificate /etc/letsencrypt/live/eunbie.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eunbie.site/privkey.pem;

    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
    }

    location /analyze-room {
        proxy_pass http://backend:8000/analyze-room;
        proxy_set_header Host $host;
    }

    location /static/ {
        proxy_pass http://backend:8000/static/;
        proxy_set_header Host $host;
    }
}
