
events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:5173;
      proxy_set_header Host $host;
    }

    location /analyze-room {
      proxy_pass http://backend:8000/analyze-room;
      proxy_set_header Host $host;
    }

    location /static/ {
      proxy_pass http://backend:8000/static/;
      proxy_set_header Host $host;
    }
  }
}
